id = "baidupan"
name = "BaiduPan"
desc = "baidu pan driver plugin"
icon = "baidupan.png"
author = ["labulakalia(labulakalia@gmail.com)"]
version = "v0.0.2"
changelog = ["fix unmarshal oper id failed"]
