package main

import (
	"encoding/json"
	"testing"

	"github.com/medianexapp/plugin_api/plugin"
)

// emby
// 电影没有自动集合  Type : "Movie" 刚好对应play info
// 电视剧默认展示 Type: "Series" 对应 play seriers ，转换为play info，在relation里展示emby的所有季
//

func TestPluginImpl(t *testing.T) {
	p := NewPluginImpl()

	p.embyAuth.Addr.StringValue.Value = "https://emby.bangumi.ca"
	p.embyAuth.User.StringValue.Value = "labulakalia"
	p.embyAuth.Password.ObscureStringValue.Value = "Ww123456@@@"

	auth, err := p.GetAuth()
	if err != nil {
		t.Fatal(err)
	}

	authData, err := p.CheckAuthMethod(&plugin.AuthMethod{
		Method: auth.AuthMethods[0].Method,
	})
	if err != nil {
		t.Fatal(err)
	}
	err = p.CheckAuthData(authData.AuthDataBytes)
	if err != nil {
		t.Fatal(err)
	}

	// 1. Test GetPluginMenus
	menus, err := p.GetPluginMenus()
	if err != nil {
		t.Fatal(err)
	}
	if len(menus.GetPluginMenus()) == 0 {
		t.Fatal("no menus returned")
	}
	t.Logf("menus %+v\n", menus.GetPluginMenus())

	// 2. Test GetPluginFilterItems
	resp, err := p.GetPluginFilterItems(menus.GetPluginMenus()[1].Menu)
	if err != nil {
		t.Fatalf("GetPluginFilterItems for menu '%s' failed: %v", menus.GetPluginMenus()[0].Menu, err)
	}
	for _, filters := range resp.Filters {
		t.Logf("filter %+v\n", filters)
	}

	// mediaInfosResp, err := p.ListPluginMediaItemInfo(&plugin.ListPluginMediaInfoRequest{
	// 	Menu:     menus.GetPluginMenus()[1].Menu,
	// 	PageSize: 5,
	// 	Page:     1,
	// })
	// if err != nil {
	// 	t.Fatal(err)
	// }
	// t.Logf("mediaInfosResp %+v\n", mediaInfosResp.MediaInfos)

	// mediaInfoDetailResp, err := p.GetPluginMediaItemDetail(&plugin.GetPluginMediaDetailRequest{
	// 	MediaInfoId: mediaInfosResp.MediaInfos[0].MediaId,
	// })
	// if err != nil {
	// 	t.Fatal(err)
	// }
	// t.Logf("mediaInfoDetailResp MediaSeries %+v\n", mediaInfoDetailResp.MediaSeries)
	// t.Logf("mediaInfoDetailResp MediaInfo %+v\n", mediaInfoDetailResp.MediaInfo)
	// for _, item := range mediaInfoDetailResp.MediaItems {
	// 	t.Logf("mediaInfoDetailResp MediaItems %+v\n", item)
	// }
	t.Log("Menu", menus.GetPluginMenus()[6].Menu)
	mediaInfosResp2, err := p.ListPluginMediaItemInfo(&plugin.ListPluginMediaInfoRequest{
		Menu:     menus.GetPluginMenus()[6].Menu,
		PageSize: 50,
		Page:     1,
	})
	if err != nil {
		t.Fatal(err)
	}
	t.Logf("mediaInfosResp %+v\n", mediaInfosResp2.MediaInfos)

	mediaInfoDetailResp2, err := p.GetPluginMediaItemDetail(&plugin.GetPluginMediaDetailRequest{
		MediaInfoId: mediaInfosResp2.MediaInfos[1].MediaId,
	})
	if err != nil {
		t.Fatal(err)
	}
	t.Logf("mediaInfoDetailResp MediaSeries %+v\n", mediaInfoDetailResp2.MediaSeries)
	t.Logf("mediaInfoDetailResp MediaInfo %+v\n", mediaInfoDetailResp2.MediaInfo)
	// t.Logf("mediaInfoDetailResp RelationMediaInfo %+v\n", mediaInfoDetailResp2.RelationMediaInfo)
	t.Logf("mediaInfoDetailResp mediaInfoDetailResp %+v\n", len(mediaInfoDetailResp2.MediaItems))

}

type AutoGenerated struct {
	DeviceProfile struct {
		MaxStaticBitrate                 int `json:"MaxStaticBitrate"`
		MaxStreamingBitrate              int `json:"MaxStreamingBitrate"`
		MusicStreamingTranscodingBitrate int `json:"MusicStreamingTranscodingBitrate"`
		DirectPlayProfiles               []struct {
			Container  string `json:"Container"`
			Type       string `json:"Type"`
			VideoCodec string `json:"VideoCodec,omitempty"`
			AudioCodec string `json:"AudioCodec,omitempty"`
		} `json:"DirectPlayProfiles"`
		TranscodingProfiles []struct {
			Container           string `json:"Container"`
			Type                string `json:"Type"`
			AudioCodec          string `json:"AudioCodec"`
			Context             string `json:"Context"`
			Protocol            string `json:"Protocol,omitempty"`
			MaxAudioChannels    string `json:"MaxAudioChannels,omitempty"`
			MinSegments         string `json:"MinSegments,omitempty"`
			BreakOnNonKeyFrames bool   `json:"BreakOnNonKeyFrames,omitempty"`
			VideoCodec          string `json:"VideoCodec,omitempty"`
			CopyTimestamps      bool   `json:"CopyTimestamps,omitempty"`
			ManifestSubtitles   string `json:"ManifestSubtitles,omitempty"`
		} `json:"TranscodingProfiles"`
		ContainerProfiles []any `json:"ContainerProfiles"`
		CodecProfiles     []struct {
			Type       string `json:"Type"`
			Codec      string `json:"Codec,omitempty"`
			Conditions []struct {
				Condition  string `json:"Condition"`
				Property   string `json:"Property"`
				Value      string `json:"Value"`
				IsRequired string `json:"IsRequired"`
			} `json:"Conditions"`
		} `json:"CodecProfiles"`
		SubtitleProfiles []struct {
			Format   string `json:"Format"`
			Method   string `json:"Method"`
			Protocol string `json:"Protocol,omitempty"`
		} `json:"SubtitleProfiles"`
		ResponseProfiles []struct {
			Type      string `json:"Type"`
			Container string `json:"Container"`
			MimeType  string `json:"MimeType"`
		} `json:"ResponseProfiles"`
	} `json:"DeviceProfile"`
}

func TestXxx(t *testing.T) {
	aaa := `{"DeviceProfile":{"MaxStaticBitrate":140000000,"MaxStreamingBitrate":140000000,"MusicStreamingTranscodingBitrate":192000,"DirectPlayProfiles":[{"Container":"mp4,m4v","Type":"Video","VideoCodec":"h264,h265,hevc,av1,vp8,vp9","AudioCodec":"mp3,aac,opus,flac,vorbis"},{"Container":"mkv","Type":"Video","VideoCodec":"h264,h265,hevc,av1,vp8,vp9","AudioCodec":"mp3,aac,opus,flac,vorbis"},{"Container":"flv","Type":"Video","VideoCodec":"h264","AudioCodec":"aac,mp3"},{"Container":"3gp","Type":"Video","VideoCodec":"","AudioCodec":"mp3,aac,opus,flac,vorbis"},{"Container":"mov","Type":"Video","VideoCodec":"h264","AudioCodec":"mp3,aac,opus,flac,vorbis"},{"Container":"opus","Type":"Audio"},{"Container":"mp3","Type":"Audio","AudioCodec":"mp3"},{"Container":"mp2,mp3","Type":"Audio","AudioCodec":"mp2"},{"Container":"aac","Type":"Audio","AudioCodec":"aac"},{"Container":"m4a","AudioCodec":"aac","Type":"Audio"},{"Container":"mp4","AudioCodec":"aac","Type":"Audio"},{"Container":"flac","Type":"Audio"},{"Container":"webma,webm","Type":"Audio"},{"Container":"wav","Type":"Audio","AudioCodec":"PCM_S16LE,PCM_S24LE"},{"Container":"ogg","Type":"Audio"},{"Container":"webm","Type":"Video","AudioCodec":"vorbis,opus","VideoCodec":"av1,VP8,VP9"}],"TranscodingProfiles":[{"Container":"aac","Type":"Audio","AudioCodec":"aac","Context":"Streaming","Protocol":"hls","MaxAudioChannels":"2","MinSegments":"1","BreakOnNonKeyFrames":false},{"Container":"aac","Type":"Audio","AudioCodec":"aac","Context":"Streaming","Protocol":"http","MaxAudioChannels":"2"},{"Container":"mp3","Type":"Audio","AudioCodec":"mp3","Context":"Streaming","Protocol":"http","MaxAudioChannels":"2"},{"Container":"opus","Type":"Audio","AudioCodec":"opus","Context":"Streaming","Protocol":"http","MaxAudioChannels":"2"},{"Container":"wav","Type":"Audio","AudioCodec":"wav","Context":"Streaming","Protocol":"http","MaxAudioChannels":"2"},{"Container":"opus","Type":"Audio","AudioCodec":"opus","Context":"Static","Protocol":"http","MaxAudioChannels":"2"},{"Container":"mp3","Type":"Audio","AudioCodec":"mp3","Context":"Static","Protocol":"http","MaxAudioChannels":"2"},{"Container":"aac","Type":"Audio","AudioCodec":"aac","Context":"Static","Protocol":"http","MaxAudioChannels":"2"},{"Container":"wav","Type":"Audio","AudioCodec":"wav","Context":"Static","Protocol":"http","MaxAudioChannels":"2"},{"Container":"mkv","Type":"Video","AudioCodec":"mp3,aac,opus,flac,vorbis","VideoCodec":"h264,h265,hevc,av1,vp8,vp9","Context":"Static","MaxAudioChannels":"2","CopyTimestamps":true},{"Container":"m4s,ts","Type":"Video","AudioCodec":"mp3,aac","VideoCodec":"h264,h265,hevc,av1","Context":"Streaming","Protocol":"hls","MaxAudioChannels":"2","MinSegments":"1","BreakOnNonKeyFrames":false,"ManifestSubtitles":"vtt"},{"Container":"webm","Type":"Video","AudioCodec":"vorbis","VideoCodec":"vpx","Context":"Streaming","Protocol":"http","MaxAudioChannels":"2"},{"Container":"mp4","Type":"Video","AudioCodec":"mp3,aac,opus,flac,vorbis","VideoCodec":"h264","Context":"Static","Protocol":"http"}],"ContainerProfiles":[],"CodecProfiles":[{"Type":"VideoAudio","Codec":"aac","Conditions":[{"Condition":"Equals","Property":"IsSecondaryAudio","Value":"false","IsRequired":"false"}]},{"Type":"VideoAudio","Conditions":[{"Condition":"Equals","Property":"IsSecondaryAudio","Value":"false","IsRequired":"false"}]},{"Type":"Video","Codec":"h264","Conditions":[{"Condition":"EqualsAny","Property":"VideoProfile","Value":"high|main|baseline|constrained baseline|high 10","IsRequired":false},{"Condition":"LessThanEqual","Property":"VideoLevel","Value":"62","IsRequired":false},{"Condition":"LessThanEqual","Property":"Width","Value":"1920","IsRequired":false}]},{"Type":"Video","Codec":"hevc","Conditions":[{"Condition":"EqualsAny","Property":"VideoCodecTag","Value":"hvc1|hev1|hevc|hdmv","IsRequired":false},{"Condition":"LessThanEqual","Property":"Width","Value":"1920","IsRequired":false}]},{"Type":"Video","Conditions":[{"Condition":"LessThanEqual","Property":"Width","Value":"1920","IsRequired":false}]}],"SubtitleProfiles":[{"Format":"vtt","Method":"Hls"},{"Format":"eia_608","Method":"VideoSideData","Protocol":"hls"},{"Format":"eia_708","Method":"VideoSideData","Protocol":"hls"},{"Format":"vtt","Method":"External"},{"Format":"ass","Method":"External"},{"Format":"ssa","Method":"External"}],"ResponseProfiles":[{"Type":"Video","Container":"m4v","MimeType":"video/mp4"}]}}`

	aa := AutoGenerated{}
	json.Unmarshal([]byte(aaa), &aa)
	t.Logf("%+v\n", aa.DeviceProfile.CodecProfiles)
	CodecProfiles, _ := json.MarshalIndent(aa.DeviceProfile.CodecProfiles, "", "  ")
	t.Logf("%s\n", CodecProfiles)
}
